### ISSUE TITLE
Warnings when using the pdf-viewer

### ISSUE THREAD

**Issue by probert94** [vaadin-component-factory/vcf-pdf-viewer#19]
The following warnings appear in the browser console, when using the pdf viewer:

```
template-renderer.js:44  WARNING: <template> inside <vaadin-select> is deprecated. Use a renderer function instead (see https://vaad.in/template-renderer)
input-field-mixin.js:78  Please define value on the <vaadin-text-field> component!
```

The first warning is related to the `vaadin-select` used for the zoom ([here](https://github.com/vaadin-component-factory/vcf-pdf-viewer/blob/main/src/vcf-pdf-viewer.js#L266-L281)).  
The second warning is related to the `vaadin-text-field` showing the current page ([here](https://github.com/vaadin-component-factory/vcf-pdf-viewer/blob/main/src/vcf-pdf-viewer.js#L283))

I am using the latest verson, together with Vaadin 24

**Comment by OlliTietavainenVaadin** [comment]
Should be fixed in https://github.com/vaadin-component-factory/vcf-pdf-viewer/pull/22 , released in version 2.0.0
